### ISSUE TITLE
player appear in rookgaard after death in main

### ISSUE THREAD

**Issue by Alucard987** [opentibiabr/otservbr-global-archived#1135]
maybe a issue in town id.  i'm using the actual source.

**Comment by majestyotbr** [comment]
Stop using capslock in issue title.

**Comment by majestyotbr** [comment]
The towns (ids) were changed in the map.

Check the towns list: https://github.com/opentibiabr/otservbr-global/blob/develop/data/global.lua#L12-#L35

**Comment by dudantas** [comment]
If that happened, it was because the player had not switched town to main.

**Comment by dudantas** [comment]
Hello, sorry for the delay in replying. The issue was closed for being unconfirmed. I did the tests and couldn't reproduce.
Make sure that:
You are using the updated datapack, source and database.
Just in case, download everything from 0 and test again.

If you are still able to reproduce the problem. Explain exactly how to reproduce, step by step, what was done. Thus, we can investigate, the information you gave is vague and so you can't do much.
