### ISSUE TITLE
Creature Convince not showing Icons.

### ISSUE THREAD

**Issue by garedgar** [opentibiabr/otservbr-global-archived#1226]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
The creatures you use the convince rune on dont show the little icon on them knowing that its your summon.

**To Reproduce**
1. Go to inquisition
2. Use your convince rune on a dreadbeast for the hellgorak boss.
3. You will be able to convince it but its hard to tell since the icon does not show on top of the creature you convince.

**Expected behavior**
Have small icon on top of the creature you convince

**Screenshots**
![convince problem](https://user-images.githubusercontent.com/49217978/81981761-5d6adf80-95f6-11ea-9579-f2ef1ad63f6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ArturKnopik** [comment]
Similarly bug on god commend `/summon "monster name" `

**Comment by gerotib** [comment]
@ArturKnopik I believe this command is not supported here anymore, but if youre still using place_summon.lua then change:
`local monster = Game.createMonster(param, position)`
to
`local monster = Game.createMonster(param, position, true, false, player)`

Convince issue itself is a bit more complicated, because monster is not created "from scratch" with Game.createMonster
