### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#1349]
.

**Comment by dudztroyer** [comment]
I don't think this is where you should look for help in this project. I'm sorry, but you might need to look elsewhere.

**Comment by JeffDev01** [comment]
> I don't think this is where you should look for help in this project. I'm sorry, but you might need to look elsewhere.

why?

**Comment by dudztroyer** [comment]
Because this is a repository to track development of a project called "OpenTibiaBR-Global" and it's issues. I don't think this is the place you should ask for "personal projects" outside of OT scope. Even if it's in OT scope (doesn't sound like... javafx... OT is mainly C++), it's not related to the forementioned project.

**Comment by ghost** [comment]
> Because this is a repository to track development of a project called "OpenTibiaBR-Global" and it's issues. I don't think this is the place you should ask for "personal projects" outside of OT scope. Even if it's in OT scope (doesn't sound like... javafx... OT is mainly C++), it's not related to the forementioned project.

Ok. Sorry
