### ISSUE TITLE
How good is the server to run today?

### ISSUE THREAD

**Issue by ncesar** [opentibiabr/otservbr-global-archived#1399]
Sorry for the silly question but is this server good to be used with many players? I mean, all these servers with 100-400 players using version 12.1 is also using this image?

Sorry again, the reason to ask this is that I see a lot of issues so I would like you guys opinions.

**Comment by dudantas** [comment]
Our repository, like any other, is in production. There are many problems to be solved and many more solved. Unfortunately (or fortunately, since it is thanks to this that we reached more than a year of active project) we depend on the collaboration of each one.
If you look at the four employees, the number of active people collaborating is low.

The answer is no. The project is still under development and we cannot guarantee that it has 100% stability. And no basis you can possibly find for sale will meet those needs.

**Comment by dudztroyer** [comment]
Complementing @dudantas answer, the best way to get the answer for your question or know if it fulfills your requirements is actually putting it into production environment. That is, putting it live and testing if it actually handles 100-400 players. 

My best bet is that it actually handles that requirements without major downsides, but it might have minor downsides which are unknown to the colloborators, and if you found a fix you can share with us so we can improve the project.

**Comment by ncesar** [comment]
Thanks guys, keep up the good job you're doing

**Comment by gpedro** [comment]
https://otservlist.org/statistics/distributions
---
If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
---

![image](https://user-images.githubusercontent.com/2898638/85924888-23cafc80-b863-11ea-975e-460303389abc.png)
