### ISSUE TITLE
library ticket mount

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1576]
![library ticket](https://user-images.githubusercontent.com/66652015/88490176-aed50a80-cf67-11ea-9591-ea6b49d4fa55.png)

**Comment by marcosvf132** [comment]
I can't see what is wrong with it. Can you describe it?

**Comment by ghost** [comment]
I guess the `library ticket` isn't working to tame the `Flying Book` (it is literally just a guess, since there's no info at all on this issue).

At least on the printscreen there's no action id on the taming item and there's no other possible correlation I could think between the creature, the item and those two characters on the screenshot.

**Comment by marcosvf132** [comment]
On the base server, library ticket is working properly to tame the flying book, but there is some errors when player fails and lose the ticket or do tame the book but do not get achievements. 
 I have a open PR where there is a possible solution for this problem, check **PR** #1570
