### ISSUE TITLE
Certain items cant be imbuid

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1585]
![cantimbui](https://user-images.githubusercontent.com/66652015/88596296-cc22db00-d032-11ea-897b-9baa78ec2018.png)

some items cant be imbuid. most can.

**Comment by ghost** [comment]
@Mortalot

1. (ENG) Mind providing us with more info so we can actually help instead of guessing how to reproduce your problem?
2. (ESP) ¿Le importaría proporcionarnos más información para que podamos ayudarlo en lugar de adivinar cómo reproducir su problema?
3. (PL) Masz ochotę podać nam więcej informacji, abyśmy mogli faktycznie pomóc, zamiast zgadywać, jak odtworzyć problem?
4. (PT) Importa-se de nos fornecer mais informações para que possamos realmente ajudar em vez de adivinhar como reproduzir seu problema?

Pick a language and write as much as you can, please, or just use the new issue (bug report) template already.

**Comment by majestyotbr** [comment]
https://tibia.fandom.com/wiki/Forgotten_Knowledge_Quest
