### ISSUE TITLE
Elemental arrows damage

### ISSUE THREAD

**Issue by torukera** [opentibiabr/otservbr-global-archived#1638]
Arrows with elemental damage doesn't have a damage range and only do a single low damage.

**Comment by attack787** [comment]
@torukera you need to be more specific when reporting a bug. In next time answer the temple issue to report a bug.

**Describe the bug**
Arrows with elemental damage doesn't have a damage range, it's always the same damage

**To Reproduce**
1. Use a bow with some elemental arrows (ids: 18437; 7850; 7839; 7840; 7838)
2. Attack a training machine to see the damage
3. You can change all elemental arrows, it's always the same damage

![image](https://user-images.githubusercontent.com/47985212/90673343-fd578b00-e22d-11ea-9ba9-16ed4445cf89.png)

Note:
- When you change the weapon (bow)  there is no increase in damage and again it's always the same damage. 
- When you rise your skills no increase in damage and again it's always the same damage. 
- When you rise level you increase in damage (only when you level up it will do more damage) and again it's always the same damage. 
- Diamond arrow have a problema with min damage (the minimum damage is very low)

The test was done with these items:
![image](https://user-images.githubusercontent.com/47985212/90674001-e5ccd200-e22e-11ea-9eed-d989d83f7562.png)

**Expected behavior**
I expected that elemental arrows have a range between minimum and maximum damage, his damage was increased when character up skills and when weapons is change.

**Desktop **
 - Windows 10

@torukera this is the way we hope you do the next report.
