### ISSUE TITLE
sql query

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1731]
![sql](https://user-images.githubusercontent.com/66652015/92336948-d8f40f00-f073-11ea-9cb2-a4d3298f4e3f.png)

**Comment by andersonfaaria** [comment]
This isn't actually an issue, it's just how the table was designed in mysql. 
In order to guarantee integrity, you cannot delete a player that has a row in quickloot_containers.

You can either delete all rows from all tables that have foreign keys prior to deleting from the players table, or you can drop the foreign key, delete it, and create it again (not recommended)
