### ISSUE TITLE
the boss The Sinister Hermit is buggy, when killed vermin swarm the server crashed

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1750]
the boss The Sinister Hermit is buggy, when killed vermin swarm the server crashed

**Comment by majestyotbr** [comment]
I'm tired of you creating issues without more details and without following the issue template. 
Explain better how what's happening, if happens errors on the distro, and other things. Or you will be blocked for a time to learn how to create issues and to contribute by sending pull requests.

**Comment by Mortalot** [comment]
you should be thankful.

**Comment by majestyotbr** [comment]
What's the difficulty to use the Bug Report issue template? 
You have been warned several times but it seems you don't understand.
i will be thankful when you create better issues here using the Bug Report issue template, help us to find the solution instead of only to paste the problem to guess, test and finally fix it.
If you want to help only creating issues, do it correctly. Thanks.

**Comment by lgrossi** [comment]
@Mortalot here is not a charity place. We are not here begging for help. We are building something in a collaborative way with dozens of different members and projects. To make it possible we have rules and people to make it work as softer as possible, without harming anyone and making collaborators time worth it. We don't want you charity, we want your serious collaboration within the rules. If you are not willing to do it, please just leave, no one is forcing you to stay. We just want you to take into consideration that we are not here to serve you but to built something nicer together. So stop this childish behavior and act as like you were in a community, please.
