### ISSUE TITLE
Failed to establish connection to the game server

### ISSUE THREAD

**Issue by DeCarvalhoJr** [opentibiabr/otservbr-global-archived#1921]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Having the server/webpage/db running im able to load the character list but not able to login, the client is even getting the boosted monster.

**To Reproduce**
clone it to your server, compile it, configure with ip, db things, run and try to connect

**Expected behavior**
It should be connecting to the game or at least send a console error

**Screenshots**
![Sem título](https://user-images.githubusercontent.com/13871000/97789335-65b3d880-1b9e-11eb-8ecb-9708d3f7256c.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Version: ubuntu 20.04 lt

**Additional context**
Just to be sure, i had it working when using (not modified) tfs 1.3 and even the johncore version.

OTServer + webserver are running on the same machine
Mysql is running on another machine

even when trying to connect im not getting any error from console

`OTServBR - Global - Version TFS 1.3

Compiled with GNU C++ version 9.3.0
Compiled on Oct 31 2020 18:44:59 for platform x64
Linked with LuaJIT 2.1.0-beta3 for Lua support

A server developed by OTServBR, Mark Samman and The Forgotten Server Developers
Visit our forum for updates, support, and resources: https://otserv.com.br/ and https://forums.otserv.com.br

Client Version: 12.51
Loading config
Establishing database connection... MySQL 8.0.22
Running database manager
Optimizing table players_online... [success]
Loading vocations
Loading items
Loading script systems
Using LuaJIT 2.1.0-beta3
Boosted creature: Son of Verminor
Loading lua libs
Loading lua scripts
Loading outfits
Checking world type... NO-PVP
Loading map
Map size: 34143x33812
Map loading time: 8.292 seconds`

**Comment by MajestyOTBR** [comment]
Which website are you using?

We have login.php compatible with GesiorAAC and MyAAC:
GesiorAAC:
https://github.com/opentibiabr/gesioraac-tibia12-login
MyAAC:
https://github.com/opentibiabr/myaac-tibia12-login

For support, you can use our discord to ask:
https://discordapp.com/invite/3NxYnyV

**Comment by majestyotbr** [comment]
Which website are you using?

We have login.php compatible with GesiorAAC and MyAAC:
GesiorAAC:
https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.3
MyAAC:
https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.6

For support, you can use our discord to ask:
https://discordapp.com/invite/3NxYnyV

**Comment by DeCarvalhoJr** [comment]
The problem isnt the login.php even using otc im not able to login to the server, im able to get the char list but not the game itself..
Anyway, i changed back to johncore one since closing it w/o giving a proper look was more important than paying attention..
IF you had read it you would see that login isnt the problem but the connection to the server..
BR sendo BR

**Comment by majestyotbr** [comment]
The issue tracker is not a support forum, you could have entered in our discord to ask but you didn't had the interest.

**Comment by MajestyOTBR** [comment]
And about the other server, it's a outdated copy from here.

**Comment by majestyotbr** [comment]
And please, stop being arrogant because i tried to help you and i gave you the link of our discord to enter there to talk, know about the project, search for tutorials, ask for support.

**Comment by majestyotbr** [comment]
I just asked you the website and invited to enter the discord to understand the problem, but you preferred to attack me without any reason.

**Comment by majestyotbr** [comment]
BR mal agradecido sendo BR mal agradecido

**Comment by majestyotbr** [comment]
Also, it's just click in the badge of discord to enter there:
https://github.com/opentibiabr/otservbr-global#docshelp

**Comment by lgrossi** [comment]
I'm not sure if you understand the concept of bug..
A bug is a malfunction of the **application** and represents a broken flow. In other words, everyone should experience this failure/malfunction when reproducing the same flow. 

Also, this server has more than 200 distributions, people with online version of it with a considerably variety of genres and customisations. More over, it's clear that the flow you're claiming to be broken is quite essential.

That said, if there was a bug or it was really broken, we would have hundred of complains and that's not the case.

So, its a missconfiguration or something you messed up from your side. Don't get me wrong, the comunity is more than happy to help you, but here is not the right communication channel to get the support, here is a place to report real bugs, that concerns and impacts all (most of) our users.

Miss configurations, doubts, specific personal issues and support are handled via discord. That's why this thread was closed and the discord was pointed out to you as the way to go.

Also, you should try be a bit more polite with people that are here to help you. I'm sorry if you have a terrible idea of yourself as a brazilian, but not all of them are the same, so please be respectful.

All the best.

**Comment by DeCarvalhoJr** [comment]
@lgrossi Hey, i've been seeing lots of topics about it, thats why i came here to state as a bug.. 
i went back to johncore one to be sure it wasnt a server problem..

I still here, since my last reply, trying to make it work.
Im using a GCP so twas easy to delete and create another instance..
i even tried many work arounds and none is helping it.. 
So if isnt in the end, maybe it may be a server end problem and for that, a bug.

btw, i dont have a terrible idea of myself as a br, its a common sense and most are jerks.. i even pref not to say that im br just to be sure people wont judge me before knowing me..

Anyway, this isnt the place, right?

i'll keep trying to make it work till i give up and go back to johncore's one.
Thanks

**Comment by gabz182** [comment]
O cara tentando ajudar e tu aí sendo arrogante, você não gosta de br pq diz que somos idiotas, mas você percebeu que você foi um idiota?
Se você quer uma comunidade mais respeitosa, comece por você mesmo.

OBS: Isso ta com cara de bad config msm.

**Comment by lgrossi** [comment]
> @lgrossi Hey, i've been seeing lots of topics about it, thats why i came here to state as a bug..
> i went back to johncore one to be sure it wasnt a server problem..
> 
> I still here, since my last reply, trying to make it work.
> Im using a GCP so twas easy to delete and create another instance..
> i even tried many work arounds and none is helping it..
> So if isnt in the end, maybe it may be a server end problem and for that, a bug.
> 
> btw, i dont have a terrible idea of myself as a br, its a common sense and most are jerks.. i even pref not to say that im br just to be sure people wont judge me before knowing me..
> 
> Anyway, this isnt the place, right?
> 
> i'll keep trying to make it work till i give up and go back to johncore's one.
> Thanks

There are considerably differences between servers, so assuming one will work just because the other one does can be a problem. As pointed out, it looks like misconfiguration. I don't know the reason myself, however, I'd pop a message in discord and see if you can get some help over there.

About brazilians, Im a Brazilian myself and I've been living and working abroad for a while now. People are very respectful with us and I see no stigma against brazilian ppl in general. In the open tibia community might be some, but just because its a poor toxic community that miss a lot of things, including respect and future vision. That's why its stucked in the same place in the last 12 years or so. Don't let people put you down because of your nationality or anything else and even more important, don't reproduce that speech with other brazilians. We should fight that, not enforce. 

See ya!

**Comment by Costallat** [comment]
You can't compare two servers just because they are OT server, we already change how the login server is made, we try to update the protocol to keep updated with the newest one. The char list is all handle by the website and after selecting your char all the information is sent to the server that will check if everything is okay, if the server is not responding that's because you have something wrong on your configuration that is sent to the client to connect to the server or something is blocking your connection to the server, but the server has nothing to do with that, if the configurations was okay it was going to answer with something.

What you did was to came here to say that you have a key that works on you old car but can't open your new car and that's a problem with the new car! :expressionless:
