### ISSUE TITLE
BUG: items.xml missing loottype crash server

### ISSUE THREAD

**Issue by ArturKnopik** [opentibiabr/otservbr-global-archived#1989]
Hello i found crash bug when editing items, when we equip a ring with a given ID, it turns into a different ring with a different ID
and first ringo have  **<attribute key="loottype" value="ring" />** and second not server will crash, checked on clean server without editing, only remove this  one line from items.xml
this make me hard time in debuging this :< 
```
<item id="2168" article="a" name="life ring">
		<attribute key="weight" value="80" />
		<attribute key="slotType" value="ring" />
		<attribute key="loottype" value="ring" />
		<attribute key="transformEquipTo" value="2205" />
		<attribute key="stopduration" value="1" />
		<attribute key="showduration" value="1" />
</item>
```

```
<item id="2205" article="a" name="life ring (faster regeneration)">
		<attribute key="weight" value="80" />
		<attribute key="slotType" value="ring" />
		** -- MISS HERE -- **
		<attribute key="decayTo" value="0" />
		<attribute key="transformDeEquipTo" value="2168" />
		<attribute key="duration" value="1200" />
		<attribute key="healthGain" value="2" />
		<attribute key="healthTicks" value="6000" />
		<attribute key="manaGain" value="8" />
		<attribute key="manaTicks" value="6000" />
		<attribute key="showduration" value="1" />
		<attribute key="showattributes" value="1" />
	</item>
```

**Comment by debone** [comment]
Thank you very much for taking the time to open this issue @ArturKnopik. While we appreciate the finding, please stick to the template it was available when you started your issue. It’s very hard to comprehend what is your issue here without reading it couple of times. Those questions and sections on the template are not by accident. I will close this one and ask you to open a new issue following the requests on the template provided
