### ISSUE TITLE
reload creaturescripts

### ISSUE THREAD

**Issue by Dorian2019** [opentibiabr/otservbr-global-archived#229]
/reload creaturescripts = crash no tfs crash log

**Comment by granoob** [comment]
the bug can not be confirmed try reviewing how your ot was configured
![image](https://user-images.githubusercontent.com/28423307/60746951-64e24680-9f58-11e9-9a5c-cfdece4e2961.png)

**Comment by gpedro** [comment]
@Dorian2019 what's the steps reproduce this issue?

**Comment by LukSrT** [comment]
A similar bug may occur when you register an event on a creature (example: kill) then delete this event from XML.  When you use the "/reload creaturescripts" command, it crashes the server.

**Comment by dudantas** [comment]
![reload creaturescript](https://user-images.githubusercontent.com/8551443/60779462-42dff400-a111-11e9-99a9-b9824dd3a512.gif)

you added some script that is crashing, download the cleaned base and check if it will happen, because here I executed directly from the repository, with only a different map, and everything went well.

closing, in the next issue show how to reproduce the problem, any news let us know that we will reopen the issue, thankful for the contact
