### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by coney4** [opentibiabr/otservbr-global-archived#23]
Is possible play this server with tibia client 11? Will you update this client or you will update only tibia 10 client ?

**Comment by omarcopires** [comment]
Hi, thanks for creating the issue.
Yes, we intend to launch client 11 and update it whenever possible, we have not done it yet for lack of testing, because one of our members has already sent us the same with client support 12.15!

Wait for some time until we officially test and launch, it should not be long.
