### ISSUE TITLE
Game.loadHouseFile for Customs maps with towns

### ISSUE THREAD

**Issue by Jqarloz** [opentibiabr/otservbr-global-archived#2301]
Hi, im test the examples of "\data\events\scripts\scheduler" 
for custom map how i can un House.xml of map? 
and how can i see the town id of custom map?  
I use in globalevents Game.loadMap and Game.loadSpawnFile

and i think that is necessary for custom maps the function  Game.loadHouseFile

Greetings

**Comment by dex-89** [comment]
Houses from a custom map cannot be loaded, because what if you turn off the new map (set the loading to false) - players lose their houses and all their content - they won't be available. Another issue is the database issue - homeowners are recorded in the database - a database conflict could arise when map loading is disabled.

**Comment by dex-89** [comment]
Houses can't be loaded by event scheduler, etc
