### ISSUE TITLE
BUG: gold pouch auto loot problem

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global-archived#2559]
Hi, i can set gold pouch to collect loot by autoloot.
I can choose gold pouch as a backpack for auto loot
Someone know how to fix it?

**Comment by kungen32** [comment]
Hi,

Gould Pouch can be added for loot money only, not works for add items or make another assignement, like Armors etc.
And works perfectly,

https://imgur.com/YSafaD1

**Comment by Zapotoczny** [comment]
Thats not true
https://streamable.com/klcith

**Comment by Zapotoczny** [comment]
> Hi,
> 
> Gould Pouch can be added for loot money only, not works for add items or make another assignement, like Armors etc.
> And works perfectly,
> 
> https://imgur.com/YSafaD1

Thats not true
https://streamable.com/klcith

**Comment by kungen32** [comment]
Totally True
Download again the version, you cannot add the gould pouch , only in gold set.

https://imgur.com/TW7zccj

**Comment by Zapotoczny** [comment]
> Totally True
> Download again the version, you cannot add the gould pouch , only in gold set.
> 
> https://imgur.com/TW7zccj

Can I somehow update the engine so as not to lose the changes I made to the files?

**Comment by kungen32** [comment]
If you made changes on your Otserv... And you are able to use Gold Pouch as a backpack.. i dont know what you change but is bad, with this you can make several bugs on your server.

IF are Scripts, just copy paste scripts from previous version to the New
All MAPS Changes you will need re-Apply again.
And then just copy your new Bosses if you got it ( goshnar ) to the server, nothing more, because the other you can change it without expecting get bugs.
