### ISSUE TITLE
Daily reward

### ISSUE THREAD

**Issue by douglera22** [opentibiabr/otservbr-global-archived#257]
Boa noite,

Fiz alguns testes, ele deixa voce pegar o premio do dia, porem nao inicia a contagem para a proxima que você pode pegar e com isso não é possivel pegar o segundo reward.

**Comment by Sargitarium** [comment]
![image](https://user-images.githubusercontent.com/42014600/64478160-7a533700-d17a-11e9-8e7a-c7b40c5afcbd.png)
- Realmente ele diz que você já pegou o item, e com isso não continua com as coletas....

**Comment by gerotib** [comment]
I actually tried to understand whole daily reward system, in order to check at which moment it should be reseted, so player can collect new daily reward. And I didnt found anything that reset storage values after server save / restart / 24h time etc (but maybe I missed something). The solution I found, and what I think is missing here is to set player storage 13412 ("avoidDouble" in dailyreward.lua file) to 0 on startup (startup.lua):
```
db.query('UPDATE `player_storage` SET `value` = 0 WHERE `player_storage`.`key` = 13412')
```
With this after every server restart player is able to collect daily reward until next one.

Explanation behind this:
In dailyreward.lua storage 13412 (avoidDouble) is set to 1 after collecting reward:
```lua
DailyReward.pickedReward = function(playerId)
  local player = Player(playerId)

  if not player then
    return false
  end

  -- Reset day streak to 0 when reaches last reward
  if player:getDayStreak() ~= 6 then
    player:setDayStreak(player:getDayStreak() + 1)
  else
    player:setDayStreak(0)
  end

  player:setStreakLevel(player:getStreakLevel() + 1)
  player:setStorageValue(DailyReward.storages.avoidDouble, Game.getLastServerSave())
  player:setNextRewardTime(Game.getLastServerSave() + DailyReward.serverTimeThreshold)
  player:getPosition():sendMagicEffect(CONST_ME_FIREWORK_YELLOW)
  return true
end
```
where `avoidDouble` is storage 13412 and `Game.getLastServerSave()` = 1, which is set in dailyRewardLib.lua. While trying to collect reward its being used to check if we already collected it today:
```lua
DailyReward.isRewardTaken = function(playerId)
  local player = Player(playerId)
  if not player then
    return false
  end
  local playerStorage = player:getStorageValue(DailyReward.storages.avoidDouble)
  if playerStorage == Game.getLastServerSave() then
    return true
  end
  return false
end
```
where `playerStorage` = 1 after collecting reward, and `Game.getLastServerSave()` = 1 (set in dailyRewardLib.lua). And the problem is that storage 13412 (avoidDouble) is never set again to 0, so player can never pick revard again.

Im sorry if its not clear, but im not really into github and explaining things here.
