### ISSUE TITLE
Some issues i found

### ISSUE THREAD

**Issue by rafael-adcp** [opentibiabr/otservbr-global-archived#530]
1. Looks like drop tracker isnt working
2. also the auto loot isnt working as well and the mana containers doesnt work as well
3. admin cant attack creatures
4. cant place itens on market to sell
5. day and night are not happening therefore some creatures in feyrist doesnt appear

**Comment by gerotib** [comment]
1. Yeah, it actually doesnt work, I think it may be because there is lacking `tmpItem->setIsLootTrackeable(true);` which [originally](https://github.com/ggmartins9/analysersv2/commit/451bbf7e22361010eca7c3babd9d50d7a8d05cf4#diff-721c64f80744c3e002360fff5827e2c8) was in monsters.cpp, but here loot is moved to lua.
2. Auto loot is not implemented yet.
3. Its intentional, but you can change it in data/xml/groups.xml (by setting flag to 0).
4. Remember to have money in your bank account, so you can pay fee needed to create offer.
5. Day and night is happening, but gods have 100% light all the time. Check on regular character. The real issue with feyrist creatures is #311

**Comment by rafael-adcp** [comment]
nice for 4 it was counting the money on my player bp but sine there was nothing at the bank it didnt work
as of 5 i was with a ms there playing around to check the map and etc etc, then it became night and night monsters didnt spawn

**Comment by dudantas** [comment]
Solved? @rafael-adcp
