### ISSUE TITLE
Client 12 AutoLoot

### ISSUE THREAD

**Issue by holydoo** [opentibiabr/otservbr-global-archived#544]
Auto loot client 12 not working.

**Comment by oualid6496** [comment]
Not implemented yet.

**Comment by dudantas** [comment]
It was removed from source because it is custom and has a lot of optimization / performance issues and it makes no sense to use system with bad and custom code.
And in the near future it will be replaced by quicklooting.

https://github.com/opentibiabr/OTServBR-Global/commit/85f92ff99bc9363883a7c84091efc48b494ca13b
