### ISSUE TITLE
Help with items.otb

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#575]
I was wondering if it would be possible to help me with the cobra items in items.otb
i mean, now i have the items in xml, i know what's the ID, but isn't working, when I invoke them with the God, automatically fall to the floor and can't be lifted at my bp or the right slot.

**Comment by dudantas** [comment]
I helped you on #562 and didn't even have the courage to say thank you, respond positively or anything... Now you want help implementing items? We do not give this kind of support and this is not a bug, since it does not even exist yet in our base ... Wait to go out or learn how to tidy up by yourself, this is not a place for support.

**Comment by ivansho92** [comment]
ohh so sorry, i'm new in the forum, i don't urderstand at 100%.
i apologize with you and i'm gratefull with you really!
Thanks so!

**Comment by dudantas** [comment]
> ohh so sorry, i'm new in the forum, i don't urderstand at 100%.
> i apologize with you and i'm gratefull with you really!
> Thanks so!

where it is, this is not a forum, it is a repository of the project.
It is not a place to support, it is a place to contribute and to report bugs.
