### ISSUE TITLE
Naginata Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#67]
Faltando 02 Dragon Lords na última sala da quest(Position: 32347, 32069, 12)

source:http://tibia.wikia.com/wiki/Naginata_Quest

**Comment by Raphaellb** [comment]
I believe this is the correct position for it 

`<spawn centerx="32348" centery="32070" centerz="12" radius="3"> 
<monster name="Dragon Lord" x="1" y="0" z="12" spawntime="3600" /> 
</spawn> 
<spawn centerx="32347" centery="32066" centerz="12" radius="3"> 
<monster name="Dragon Lord" x="1" y="0" z="12" spawntime="3600" /> 
</spawn>`

i didn't create a pull request because all the files under world are compressed into rar. Feel free to change the spawn time. The wiki says a slow respawn.

**Comment by dudantas** [comment]
@Raphaellb thanks, fixed
