### ISSUE TITLE
Terceira Prey

### ISSUE THREAD

**Issue by luisbill1** [opentibiabr/otservbr-global-archived#696]
Alguem sabe como desativa a terceira prey ou botar apenas pra comprar na loja? os chares criados estão já logando com a terceira prey liberada

**Comment by gerotib** [comment]
As I remember, client was crashing with 2 of 3 prey slots unlocked. but I dont know how to solve this.

**Comment by lBaah** [comment]
@gerotib the solution to client crashing is to change prey information on source to uint_16 instead of uint_8. Take a look if there are any function related to prey that sends uint_8 data instead of uint_16. https://github.com/opentibiabr/OTServBR-Global/search?q=prey&unscoped_q=prey

@luisbill1 this is not a bug.
https://github.com/opentibiabr/OTServBR-Global/blob/bdae90220c31d78b3fd0e77ea2d550f3e65944a5/src/iologindata.cpp#L261
Every slot is being unlocked in this point.

So this don't work (no locked slots):
https://github.com/opentibiabr/OTServBR-Global/blob/50f2fb65f06b043f46df9e12dbfb2097f91ac72f/data/modules/scripts/prey%20system/prey.lua#L428

**Comment by gerotib** [comment]
@lBaah generally preys works fine and doesnt crash, only when I try to set one/ couple of them to locked (quickly set with onLogin) it crashes. As I looked at pre-rewrite prey system it was [checking](https://github.com/opentibiabr/OTServBR-Global/commit/f0f4f804a3aac3207b0c436c048403a2e2fe8527#diff-130f4637aca1e40f02ed0cd7c74d8894L138) if slot is unlocked before sending prey data.
If I set for expample third slot to LOCKED, "small window" does crash while sending prey data for all slots, but doesnt crash if I set this for only 1st and 2nd slot. (changing [this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/creaturescripts/scripts/others/login.lua#L66) to `for slot = CONST_PREY_SLOT_FIRST, CONST_PREY_SLOT_SECOND do`). But while opening real prey window it does crash. So I think that this prey data for locked slot should not be sent, or network message for this is wrong.

**Comment by luisbill1** [comment]
@lBaah Thanks bro

**Comment by lBaah** [comment]
@gerotib Sorry for the delay.
If you lock prey you should truncate all prey info on database, so you'll be fine

**Comment by majestyotbr** [comment]
#853
