### ISSUE TITLE
"Infront of" Spells, are bugged.

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#780]
Magias como, exori min / exevo vis hur, e outras que tem "start" no sqm da frente, estão 'bugadas'

Vídeo explicativo:
https://www.youtube.com/watch?v=ooQz6yTFE1A

**Comment by lBaah** [comment]
Adiciona as tags conforme e testa:
https://github.com/opentibiabr/otservbr-global/blob/develop/src/spells.cpp#L553

Depois faz um PR com a correção.

https://www.digitalocean.com/community/tutorials/como-criar-um-pull-request-no-github-pt

**Comment by Lycanzito** [comment]
> Adiciona as tags conforme e testa:
> https://github.com/opentibiabr/otservbr-global/blob/develop/src/spells.cpp#L553
> 
> Depois faz um PR com a correção.
> 
> https://www.digitalocean.com/community/tutorials/como-criar-um-pull-request-no-github-pt

as tags estão iguais.
```

	if ((attr = node.attribute("blocking"))) {
		blockingSolid = attr.as_bool();
		blockingCreature = blockingSolid;
	}

	if ((attr = node.attribute("blocktype"))) {
		std::string tmpStrValue = asLowerCaseString(attr.as_string());
		if (tmpStrValue == "all") {
			blockingSolid = true;
			blockingCreature = true;
		} else if (tmpStrValue == "solid") {
			blockingSolid = true;
		} else if (tmpStrValue == "creature") {
			blockingCreature = true;
		} else {
			std::cout << "[Warning - Spell::configureSpell] Blocktype \"" << attr.as_string() << "\" does not exist." << std::endl;
		}
	}
```

**Comment by Lycanzito** [comment]
@lBaah Alguma novidade ? =/

**Comment by vankk** [comment]
Try comment [this variable condition](https://github.com/opentibiabr/OTServBR-Global/blob/master/src/combat.cpp#L234-L236) and replace 
```cpp
if (params.impactEffect != CONST_ME_NONE) {
	Game::addMagicEffect(list, tile->getPosition(), params.impactEffect);
}
```
to
```cpp
if (params.impactEffect != CONST_ME_NONE) {
	if (tile->getGround() && !tile->hasProperty(CONST_PROP_BLOCKPROJECTILE) && !tile->hasProperty(CONST_PROP_BLOCKSOLID)) {
		Game::addMagicEffect(list, tile->getPosition(), params.impactEffect);
	}
}
```
I don't know the side effects of this changes, the exchange is just to avoid the effects been displayed where doesn't have any sense (empty floors)

**Comment by Lycanzito** [comment]
Didnt work here. Only errors come from these changes T.T

**Comment by Lycanzito** [comment]
After the edit, work 50% fine,
![image](https://user-images.githubusercontent.com/52710697/71549741-3b532680-29a1-11ea-819a-bdf84dad7baa.png)


the problem is the walls now.
![image](https://user-images.githubusercontent.com/52710697/71549737-32faeb80-29a1-11ea-8e74-be41a5fa6d82.png)

**Comment by gpedro** [comment]
related to otland/forgottenserver#2891

**Comment by Lycanzito** [comment]
> related to [otland/forgottenserver#2891](https://github.com/otland/forgottenserver/issues/2891)

ty

**Comment by beats-dh** [comment]
https://github.com/otland/forgottenserver/pull/3390
Does that solve it?

**Comment by Zbizu** [comment]
@Beats-Dh no, because the entire logic of area spells is flawed. There is no check for pathing at all.

When the area spell is cast, it goes through these functions (tfs master branch):
`spells.cpp -> castSpell -> executeCastSpell -> spell lua file (eg. fire_wave.lua) -> onCastSpell -> luascript.cpp -> combat:execute -> combat.cpp -> doCombat(caster, position)`

it reads spell area and checks for specific tiles availability, but doesn't check if they're accessible

in this repo combat.cpp calls another function, but it uses identical logic, see [your repo](https://github.com/opentibiabr/otservbr-global/blob/f896a3c8ed9c18b87b0a13fb6605e86c7896899d/src/creatures/combat/combat.cpp#L755) and [tfs](https://github.com/otland/forgottenserver/blob/5ca26836f450af523da57ef6d441e206bbdc2df7/src/combat.cpp#L713)

If anyone bothers coding a path check for area spells, a new function would be needed to return a list of points in the path and merge it with a matrix while doing checks. Here's how it can be implemented: [link to comment](https://github.com/otland/forgottenserver/issues/2891#issuecomment-832249624)

**Comment by beats-dh** [comment]
I tested it and saw no problem.
